# Generated by Django 5.0.2 on 2024-02-23 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_remove_vehicle_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vendor'),
        ),
    ]
