# Generated by Django 5.0.2 on 2024-02-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_remove_vehicle_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitycheck',
            name='pass_status',
        ),
        migrations.RemoveField(
            model_name='qualitycheck',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='po_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='quality_result',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
